"""Add last_seen_message_id

Revision ID: 9e57f82b2dd1
Revises: a1a5dc8f68ba
Create Date: 2026-02-22 22:04:30.844463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e57f82b2dd1'
down_revision: Union[str, Sequence[str], None] = 'a1a5dc8f68ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_participants', sa.Column('last_seen_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'conversation_participants', 'messages', ['last_seen_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversation_participants', type_='foreignkey')
    op.drop_column('conversation_participants', 'last_seen_message_id')
    # ### end Alembic commands ###
