"""Add is_archived and is_active

Revision ID: a1a5dc8f68ba
Revises: fe17aa31175d
Create Date: 2026-02-22 21:47:48.732960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1a5dc8f68ba'
down_revision: Union[str, Sequence[str], None] = 'fe17aa31175d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_participants', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('conversations', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('conversations', 'is_archived')
    op.drop_column('conversation_participants', 'is_active')
    # ### end Alembic commands ###
